#!/bin/sh

# [ -n "$(ls /etc/pre_install)" ] && opkg install /etc/pre_install/*.ipk --force-depends
[ -n "$(ls /etc/pre_install)" ] && opkg install /etc/pre_install/*.ipk

rm -rf /etc/pre_install

exit 0
